# docker run -d --device /dev/kfd --device /dev/dri -v ollama:/root/.ollama -p 11434:11434 --name ollama ollama/ollama:rocm
services:
  ollama:
    image: ollama/ollama
    container_name: ollama
    restart: unless-stopped
    volumes:
      - ollama:/root/.ollama
    ports:
      - "11434:11434"
  postgres:
    image: pgvector/pgvector:0.8.0-pg17
    restart: unless-stopped
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: vector_db
    ports:
      - "5432:5432"
    volumes:
      - ./vector_db:/var/lib/postgresql/data
      - ./db:/docker-entrypoint-initdb.d/
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      PG_CONNECTION_STRING: "postgresql+psycopg://user:password@postgres:5432/vector_db"
      OLLAMA_BASE_URL: "http://ollama:11434"
    depends_on:
      - postgres
      - ollama
    ports:
      - "5000:5000"
volumes:
  ollama:
