# docker compose exec ollama ollama pull 
# mistral:7b-instruct-q4_K_M
# gemma3:4b-it-qat
# docker compose exec ollama ollama pull nomic-embed-text:latest
# ollama pull mistral:7b-instruct-q4_K_M

services:
  ollama:
    image: ollama/ollama
    container_name: ollama
    restart: unless-stopped
    volumes:
      - ollama:/root/.ollama
    ports:
      - "11434:11434"
  postgres:
    image: pgvector/pgvector:pg17
    restart: unless-stopped
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: vector_db
    ports:
      - "5432:5432"
    volumes:
      - vector_db:/var/lib/postgresql/data
      - ./db:/docker-entrypoint-initdb.d/
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      PG_CONNECTION_STRING: "postgresql+psycopg://user:password@postgres:5432/vector_db"
      OLLAMA_BASE_URL: http://host.docker.internal:11434
    #depends_on:
      #- postgres
      #- ollama
    ports:
      - "5050:5000"

volumes:
  ollama:
  vector_db:
